server:
  port: 8004

spring:
  application:
    name: api-server-1
  sleuth:
    sampler:
      percentage: 1.0
#  zipkin:
     #base-url: http://localhost:9411
#     locator:
#       discovery:
#         enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level: info
  file: target/api-server-1.log

management:
  info:
    git:
      enabled: true
      mode: full
  security:
    enabled: false


info:
  app1:
    version: ${project.version}
    group: ${project.group}

swagger:
  enable: true
  api-info:
    description: User接口
    license: http://www.test.com
    license-url: http://www.test.com
    terms-of-service-url: http://www.test.com
    title: User接口
    version: 2.5.1
    contact:
      email: test@qq.com
      name: test
      url: http://www.test.com
  docket:
    base-package: com.jean.cloud.server.api
    group-name: user
    pathMapping: /
