export const RESULT_DATA = 'RESULT_DATA';

export const LIST_LOADING = 'LIST_LOADING';

export const ADD_DIALOG_OPEN_FLAG = 'ADD_DIALOG_OPEN_FLAG';

export const BEFORE_ADD_DIALOG_OPEN = 'BEFORE_ADD_DIALOG_OPEN';

export const AFTER_ADD_SUBMIT = 'AFTER_ADD_SUBMIT';

export const EDIT_DIALOG_OPEN_FLAG = 'EDIT_DIALOG_OPEN_FLAG';

export const ADD_BUTTON_LOADING = 'ADD_BUTTON_LOADING';

export const EDIT_BUTTON_LOADING = 'EDIT_BUTTON_LOADING';

export const ADD_FORM_DATA = 'ADD_FORM_DATA';

export const EDIT_FORM_DATA = 'EDIT_FORM_DATA';

export const QUERY_PARAMS = 'QUERY_PARAMS';

export const COMMON_PARAMS = 'COMMON_PARAMS';

export const CUSTOMER_PARAMS = 'CUSTOMER_PARAMS';

export const ADD_FORM_RULES = 'ADD_FORM_RULES';

export const EDIT_FORM_RULES = 'EDIT_FORM_RULES';

