server:
  port: 8080

spring:
  application:
    name: user-service-jpa
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.52.2.66:3306/user_jpa?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
#    properties:
#      hibernate.format_sql: true

swagger:
  enable: true
  api-info:
    description: User接口
    license:
      name: test
      url: http://www.test.com
    terms-of-service-url: http://www.test.com
    title: User接口
    version: 1.0
    contact:
      email: zhangsan@qq.com
      name: zhangsan
      url: http://www.test.com
  docket:
    enable: true
    groupName: USER
    pathPrefix: /
    apiPackage: com.jean.user.api
  responseMessage:
    - code: 200
      message: ok
    - code: 400
      message: 非法请求
    - code: 500
      message: 服务器忙