server:
  port: 8006
spring:
  application:
    name: es-server
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.52.2.66:9300

info:
  config:
    version: ${project.version}
    group: ${project.group}