server:
  port: 8769
spring:
  application:
    name: turbine-server
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  datasource:
#    schema: classpath:mysql.sql
#    url: jdbc:mysql://localhost:3306/zipkin
#    username: root
#    password: root
#    continue-on-error: true
#    initialize: true
turbine:
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: API-SERVER-1,API-SERVER-2,ZIPKIN-SERVER-STREAM # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
  # 3. 当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level: debug

info:
  turbine:
    version: ${project.version}
    group: ${project.group}