server:
  port: 9411
spring:
  application:
    name: zipkin-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level: debug

zipkin:
  storage:
    type: mysql
    mysql:
      host: localhost
      port: 3306
      username: root
      password: root
      db: zipkin
      max-active: 10
      use-ssl: false

info:
  zipkin:
    version: {project.version}
    group: {project.group}