server:
  port: 8005

spring:
  application:
    name: api-server-2
  sleuth:
    sampler:
      percentage: 1.0
#  zipkin:
     #base-url: http://localhost:9411
#     locator:
#       discovery:
#         enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    root: WARN
    com.jean: DEBUG
    org.springframework: WARN
  file: target/${spring.application.name}.log

management:
  info:
    git:
      enabled: true
      mode: full
  security:
    enabled: false

info:
  app2:
    version: ${project.version}
    group: ${project.group}

mylog:
  expression: execution(* com.jean.cloud.server.api..*.*(..))||execution(* com.jean.cloud.server.listener..*.*(..))
  location: locationxxxxxxxxxxxxxxxxxxxxxx
  logParams: true
  logResult: true
  logCost: true
  remoteUrl: http://10.52.2.204:8088/db