server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        db:
          uri: https://github.com/jinshubao/config-server.git
          search-paths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.52.88.199:7013/eureka/

info:
  config:
    version: ${project.version}
    group: ${project.group}