server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinshubao/config-server.git
          search-paths: cloud-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  config:
    version: ${project.version}
    group: ${project.group}