server:
  port: 8080

spring:
  application:
    name: swagger-test

info:
  swagger-test:
    version: ${project.version}
    group: ${project.group}

swagger:
  enable: true
  api-info:
    title: 接口
    description: API接口
    terms-of-service-url: http://www.test.com
    license:
      name: test
      url: http://www.test.com
    version: 1.0
    contact:
      email: zhangsan@qq.com
      name: zhangsan
      url: http://www.test.com
  dockets:
    user:
      groupName: USER
      paths: /user/**
    order:
      groupName: ORDER
      pathPrefix: /order/**
